version: '3.3'

services:
  app:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: annotation-app:latest
    container_name: annotation-app
    restart: unless-stopped
    # env_file:
    #   - .env
    # environment:
    #   - MONGO_HOST=mongo
    ports:
      - 9557:3000
    volumes:
      - ./data:/app/fe/data
    networks:
      - annotation-app-net

networks:
  annotation-app-net:

volumes:
  annotation_data:
